book-a-reading-room-visit.web/Properties/launchSettings.json, book-a-reading-room-visit.web/Startup.cs, book-a-reading-room-visit.web/Views/Booking/BookingConfirmation.cshtml, book-a-reading-room-visit.web/Views/Booking/SecureBooking.cshtml, book-a-reading-room-visit.web/Views/DocumentOrder/DocumentOrder.cshtml, book-a-reading-room-visit.web/Views/DocumentOrder/OrderDocuments.cshtml, book-a-reading-room-visit.web/Views/Home/Availability.cshtml, book-a-reading-room-visit.web/Views/Home/Index.cshtml
Updated the url with controller and action based url.
=> Added route directory for the application 

book-a-reading-room-visit.api/Controllers/BookingController.cs, book-a-reading-room-visit.api/Models/BookingSearchModel.cs, book-a-reading-room-visit.api/Service/Impl/BookingService.cs, book-a-reading-room-visit.api/Service/Interface/IBookingService.cs, book-a-reading-room-visit.test/BookingIntegrationTest.cs, book-a-reading-room-visit.test/Init/CustomWebApplicationFactory.cs, book-a-reading-room-visit.test/Init/TestData.cs
Added API functionality to search for bookings using zero, one or more of the following: Reader Ticket, Booking Reference, Visit Start Date
=> API Booking Search

book-a-reading-room-visit.api/Service/Impl/BookingService.cs
Enhanced the Booking search to bring back additional related information.
This version works with the enhanced Digital Back Office in the $/Digital Back Office/Projects/Main-S3-Kew-Booking branch in Azure DevOps
=> Kew Booking search enhancement.

book-a-reading-room-visit.api/Controllers/BookingController.cs, book-a-reading-room-visit.api/Service/Impl/BookingService.cs, book-a-reading-room-visit.api/Service/Interface/IBookingService.cs, book-a-reading-room-visit.model/KewBookingSeatUpdateModel.cs
Now says who made the update and allows for a comment to be added.
=> Enhancements to seat booking update functionality.  

book-a-reading-room-visit.api/Service/Impl/BookingService.cs, book-a-reading-room-visit.model/BookingModel.cs
So it can be displayed in the Back Office.
=> Added booking type description to details model.

book-a-reading-room-visit.api/Controllers/AvailabilityController.cs, book-a-reading-room-visit.api/Service/Impl/AvailabilityService.cs, book-a-reading-room-visit.api/Service/Interface/IAvailabilityService.cs, book-a-reading-room-visit.data/Script/2.look up data.sql, book-a-reading-room-visit.model/SeatTypes.cs
Added managerial discretion seat type.  Amended call to get all seats for a date to specify whether or not this seat type should be included in the results.  Seats returned by this call are now ordered by seat number,
=> managerial Discretion seat type added.

book-a-reading-room-visit.api/Controllers/BookingController.cs, book-a-reading-room-visit.api/Service/Impl/BookingService.cs, book-a-reading-room-visit.api/Service/Interface/IBookingService.cs, book-a-reading-room-visit.api/appsettings.json, book-a-reading-room-visit.web/Controllers/BookingController.cs, book-a-reading-room-visit.web/Helper/Constants.cs, book-a-reading-room-visit.web/Properties/launchSettings.json, book-a-reading-room-visit.web/Service/Impl/BookingService.cs, book-a-reading-room-visit.web/Service/Interface/IBookingService.cs
Made it configurable for testing purpose
=> Included reader ticket validation based on the order limit

book-a-reading-room-visit.web/Controllers/BookingController.cs, book-a-reading-room-visit.web/Models/BookingViewModel.cs, book-a-reading-room-visit.web/Views/Booking/SecureBooking.cshtml
Fixed the server side time issue when validation error occurs.
=> Added remaining time in seconds

book-a-reading-room-visit.web/Views/Shared/_Layout.cshtml
Hi @gtvj,
Could you have a quick look at this PR; it just adds a format detection meta tag to the `<head>` in the layout file.
Thank you
=> Add format-detection meta tag

book-a-reading-room-visit.web/Views/Shared/AboutTheBookAReadingRoomVisitService.cshtml, book-a-reading-room-visit.web/Views/Shared/Partials/_Footer.cshtml, book-a-reading-room-visit.web/Views/Shared/TermsOfUse.cshtml
Hi @gtvj,
Could you have a look at this PR? Thank you
=> Update about and terms of use pages

book-a-reading-room-visit.web/Views/Shared/Partials/_ContactFooter.cshtml
Hi @gtvj/@AshTNA,
Could you have a quick look at this PR? Thank you
=> Update contact us link

book-a-reading-room-visit.web/Helper/Constants.cs, book-a-reading-room-visit.web/Helper/CustomHtmlValidation.cs, book-a-reading-room-visit.web/Helper/ValidateDocumentOrder.cs, book-a-reading-room-visit.web/Models/DocumentOrderViewModel.cs
added custom validation for multiline html tag
updated additional validation on reference
=> Validation Included

book-a-reading-room-visit.web/Views/Home/Availability.cshtml, book-a-reading-room-visit.web/Views/Home/Index.cshtml
Hi @gtvj,
This PR adds a ternary condition to pluralise the date on the home page and availability page. Please could you merge if you are happy? Thank you
=> Add ternary condition for date pluralisation

book-a-reading-room-visit.api/EmailTemplate/BookingConfirmation.xslt, book-a-reading-room-visit.api/EmailTemplate/Text/BookingConfirmation.txt
Hi @Puththiran,
Could you have a look at this PR and merge if you are happy? Thank you.
=> Update confirmation email

book-a-reading-room-visit.data/Migrations/20210624092637_check-multi-day-visit-availability.cs
Sorry minor change to sproc following further testing.
=> Fix to SQL sproc.

book-a-reading-room-visit.api/EmailTemplate/AutomaticCancellation.xslt, book-a-reading-room-visit.api/EmailTemplate/BookingCancellation.xslt, book-a-reading-room-visit.api/EmailTemplate/BookingConfirmation.xslt, book-a-reading-room-visit.api/EmailTemplate/InvalidOrderReminder.xslt, book-a-reading-room-visit.api/EmailTemplate/ReservationConfirmation.xslt, book-a-reading-room-visit.api/EmailTemplate/Text/AutomaticCancellation.txt, book-a-reading-room-visit.api/EmailTemplate/Text/BookingCancellation.txt, book-a-reading-room-visit.api/EmailTemplate/Text/BookingConfirmation.txt, book-a-reading-room-visit.api/EmailTemplate/Text/DSDBookingConfirmation.txt, book-a-reading-room-visit.api/EmailTemplate/Text/InvalidOrderReminder.txt, book-a-reading-room-visit.api/EmailTemplate/Text/ReservationConfirmation.txt, book-a-reading-room-visit.api/EmailTemplate/Text/ValidOrderReminder.txt, book-a-reading-room-visit.api/EmailTemplate/ValidOrderReminder.xslt, book-a-reading-room-visit.test/EmailTemplate/Text/AutomaticCancellation.txt, book-a-reading-room-visit.test/EmailTemplate/Text/BookingCancellation.txt, book-a-reading-room-visit.test/EmailTemplate/Text/BookingConfirmation.txt, book-a-reading-room-visit.test/EmailTemplate/Text/DSDBookingConfirmation.txt, book-a-reading-room-visit.test/EmailTemplate/Text/InvalidOrderReminder.txt, book-a-reading-room-visit.test/EmailTemplate/Text/ReservationConfirmation.txt, book-a-reading-room-visit.test/EmailTemplate/Text/ValidOrderReminder.txt, book-a-reading-room-visit.web/Controllers/BookingController.cs, book-a-reading-room-visit.web/Helper/Constants.cs, book-a-reading-room-visit.web/Models/BookingViewModel.cs, book-a-reading-room-visit.web/Views/Booking/BookingConfirmation.cshtml, book-a-reading-room-visit.web/Views/Booking/CancellationConfirmation.cshtml, book-a-reading-room-visit.web/Views/Booking/SecureBooking.cshtml, book-a-reading-room-visit.web/Views/DocumentOrder/ContinueLater.cshtml, book-a-reading-room-visit.web/Views/DocumentOrder/OrderComplete.cshtml, book-a-reading-room-visit.web/Views/DocumentOrder/OrderDocuments.cshtml
KBS-314, KBS-315 & KBS-316 features included
=> 20-July-2021 Feature release

book-a-reading-room-visit.api/EmailTemplate/DSDBookingConfirmation.xslt, book-a-reading-room-visit.api/Service/Impl/EmailService.cs
Email template and logic updated to print in A4 sheet
=> DSD email update

book-a-reading-room-visit.api/Properties/launchSettings.json, book-a-reading-room-visit.api/Service/Impl/AvailabilityService.cs, book-a-reading-room-visit.web/Controllers/HomeController.cs, book-a-reading-room-visit.web/Helper/MiddlewareExtensions.cs, book-a-reading-room-visit.web/Helper/UpdateGroup.cs, book-a-reading-room-visit.web/Models/AvailabilityViewModel.cs, book-a-reading-room-visit.web/Properties/launchSettings.json, book-a-reading-room-visit.web/Views/Home/Availability.cshtml
- removed the two/one day bulk order booking logic
- included no-store cache to exclude from the AWS cloud front
=> No-cache included and code refactored

book-a-reading-room-visit.web/Controllers/BookingController.cs, book-a-reading-room-visit.web/Helper/CustomEmailValidation.cs, book-a-reading-room-visit.web/Models/BookingViewModel.cs, book-a-reading-room-visit.web/book-a-reading-room-visit.web.csproj
added SSO custom email validator
=> removed the default email validator

book-a-reading-room-visit.web/Views/Shared/Partials/_FooterContent.cshtml
Hi @JamesWChan 
Would you be able to merge this?
It fixes some old links in the footer which have been replaced with new links.
Thanks :+1:
=> Replace old footer links with newer links
